spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendar
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_batch_fetch_size: 100

server:
  port: 8080
jwt:
  secret: a2ltbGlta2ltY2hhbmp1bmthbmdzdXllb25naG8=
  expiration: 86400000