## 개발환경 설정
spring:
    h2:
      console:
          enabled: true
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        database: H2
        show-sql: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
server:
    port: 8080
jwt:
    secret: kimlimkimchanjunkangsuyeongho
    expiredTime: 86400000
