
spring:
    ## DB?? ????
    datasource:
        url: jdbc:postgresql://localhost:5432/calendar
        username: postgres
        password: 1234
        driver-class-name: org.postgresql.Driver

    jpa:
        database: POSTGRESQL
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8081
jwt:
    secret: 김임김강준찬호준수
    expiredTime: 86400000
