spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
      driver-class-name: org.h2.Driver

  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true