spring:
  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _HIS
            store_data_at_delete: true

server:
  port: 8080
jwt:
  secret: a2ltbGlta2ltY2hhbmp1bmthbmdzdXllb25naG8=
  expiration: 1800000
  refreshExpiration: 86400000

admin-user:
  name: admin
  password: khkimcsjylim1234
  username: admin

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    configprops:
      roles: ADMIN
      show-values: when_authorized
    env:
      roles: ADMIN
      show-values: when_authorized
    health:
      roles: ADMIN
      show-details: when_authorized
    shutdown:
      enabled: true
  info:
    java:
      enabled: true
    os:
      enabled: true
  simple:
    metrics:
      export:
        enabled: true
        step: 24h